### ISSUE TITLE
helm-navi not working 

### ISSUE THREAD

**Issue by chrisoswald** [emacs-helm/helm-navi#4]
after installation no helm-navi command is working always the error:

` Symbol’s value as variable is void: outline-promotion-headings`

Its a fresh install without any configuration, (emacs 26, linuxmint 19.3)

Any suggestions or ideas?

Thanks,
Christian

**Comment by GreyGhostIX** [comment]
EDIT: I just noticed after typing this out that there is a two year old pull request that would fixes this. #3 
Looks like outline mode doen't define this var anymore. I will leave my patch in case its helpful. 

If anyone is still looking for a fix I had this problem also, on spacemacs, emacs 26, with outshine layer installed.

It fixed it for me to replace every instance of `outline-promotion-headings` with `outshine-promotion-headings`, since they were actually defined by the spacemacs outshine package. It's a local variable set dynamically for different files, so just copying the variable at init didn't work.

You could also consider define the variable yourself if you only need it for one mode. For reference in org mode it looks like:
```
((";;; " . 1)
 (";;;; " . 2)
 (";;;;; " . 3)
  and so on ... )
```
If you actually have the variable defined somewhere else, like I did in outshine, you can also copy at the time of calling the function with something like:
```
(defun my-helm-navi ()
  (interactive)
  (if (boundp 'outline-promotion-headings)
      (helm-navi)
    (setq-local outline-promotion-headings outshine-promotion-headings)
    (helm-navi)))
```
and then use that function as a replacement.

**Comment by alphapapa** [comment]
#3 is merged, so this is fixed.  As I said on that PR:

> Thanks.  I would have been glad to merge this...two years ago, but since this repo is under the emacs-helm organization, I can't easily see its issues and PRs in my GitHub searches along with my other repos, and its notifications are easily lost among others in the list.

One of the disadvantages to having one's repos spread among different GitHub organizations...
